### ISSUE TITLE
Associate Job Template to Workflow

### ISSUE THREAD

**Issue by pmannozg** [ilijamt/terraform-provider-awx#111]
Hello,

I see you have awx_job_template and awx_workflow_job_template resources but no way to associate a job template to a workflow?  Am I missing something?

Thanks,
Paul

**Comment by firdousreshi** [comment]
/api/v2/workflow_job_template_nodes/

anything on this.


{
    "extra_data": {},
    "inventory": null,
    "scm_branch": "",
    "job_type": null,
    "job_tags": "",
    "skip_tags": "",
    "limit": "",
    "diff_mode": null,
    "verbosity": null,
    "execution_environment": null,
    "forks": null,
    "job_slice_count": null,
    "timeout": null,
    "workflow_job_template": null,
    "unified_job_template": null,
    "all_parents_must_converge": false,
    "identifier": ""
}
