### ISSUE TITLE
Please add instance group under resource awx_job_template 

### ISSUE THREAD

**Issue by Sujishv** [ilijamt/terraform-provider-awx#70]
Hi, 
Can you add a option to select instance group while creating awx templates 

Thanks 
Sujish

**Comment by ilijamt** [comment]
Hi, Yeah, this seems like it's an extra call after you create a Job template. It will be better if it’s just a new resource to assign it. I'll take care of it this week.

**Comment by ilijamt** [comment]
@Sujishv can you test now? I've added a resource to associate the IDs. Here is an example.

```
resource "awx_job_template_associate_instance_group" "ig" {
  instance_group_id = awx_instance_group.ig.id
  job_template_id   = awx_job_template.instance_group.id
}
```

New release is up

* https://github.com/ilijamt/terraform-provider-awx/releases/tag/v0.1.5
* https://registry.terraform.io/providers/ilijamt/awx/0.1.5

**Comment by Sujishv** [comment]
Thanks it s working, one doubt why cant we cant directly under resource awx_job_template ?

**Comment by ilijamt** [comment]
It's a separate call under the AWX API, it's not part of the creation of a job template.
