### ISSUE TITLE
 awx_job_template_associate_credential import failed 

### ISSUE THREAD

**Issue by Sujishv** [ilijamt/terraform-provider-awx#74]
I was trying to import my manually created templates credentials and getting below error. can you please guide me here

import {
  to = awx_job_template_associate_credential.fetch_sdts
  id = 18
}

│ Error: Unable to import state for JobTemplate association, invalid format.
│
│ requires the identifier to be set to <job_template_id>/<credential_id>, currently set to 18

sametime i could successfully import templates using below import

import {
  to = awx_job_template.fetch_sdts
  id = 18
}

**Comment by ilijamt** [comment]
The ID for import is a combination of two things. If you check https://github.com/ilijamt/terraform-provider-awx/blob/main/docs/resources/job_template_associate_credential.md

Then the ID should be `<job_template_id>/<credential_id>` 

```
import {
    to = awx_job_template_associate_credential.fetch_sdts
    id = "${awx_job_template.fetch_sdts.id}/18"
}
```

Can you try this and let me know if it works?

**Comment by Sujishv** [comment]
Thank you so much its working.
