### ISSUE TITLE
Support to authenticate with user token

### ISSUE THREAD

**Issue by srtab** [ilijamt/terraform-provider-awx#82]
Hi @ilijamt,

Congrats for the excellent work! 

I'm using your provider to manage our Tower/AWX instance, and it will be nice to allow authenticating using only a user token to avoid using credentials from the user and make it easier to rotate tokens.
Do you think it might make sense to add this feature?

**Comment by ilijamt** [comment]
I'll look into it. Shouldn't be too difficult to add. I guess you are talking about the Personal Access Tokens for a user, right? 
https://docs.ansible.com/ansible-tower/latest/html/administration/oauth2_token_auth.html

**Comment by srtab** [comment]
Right @ilijamt :D 
Thanks!

**Comment by ilijamt** [comment]
With the new release, PAT should be usable.
