### ISSUE TITLE
Feature: Instance groups association with teams

### ISSUE THREAD

**Issue by reshifirdous** [ilijamt/terraform-provider-awx#94]
I would like to see if we could implement roles to team of type instance groups. I didnt find any documenation or any such examples that could point if this is already been developed, but as far as i check it seems we dont have it implemented yet. Would it be possible to get this included in the stack?

**Comment by ilijamt** [comment]
Hi @reshifirdous can you point me to the API in question for association? I need to check.

**Comment by ilijamt** [comment]
https://github.com/ilijamt/terraform-provider-awx/blob/b9223490c7687b395d627efbdf7906dcd9e49c80/examples/roles/main.tf#L68-L79

**Comment by ilijamt** [comment]
You can try the new releases depending on which version you use.

* [v23.5.1-0](https://github.com/ilijamt/terraform-provider-awx/releases/tag/v23.5.1-0)
* [v23.6.0-0](https://github.com/ilijamt/terraform-provider-awx/releases/tag/v23.6.0-0)
* [v23.7.0-0](https://github.com/ilijamt/terraform-provider-awx/releases/tag/v23.7.0-0)
* [v23.8.1-0](https://github.com/ilijamt/terraform-provider-awx/releases/tag/v23.8.1-0)
